import requests
import urllib3
import ipaddress
try:
    from aegis.core.display import display
except ImportError:
    pass

# Disable SSL warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

PRIORITY = 20
TYPE = "Cloud Recon"
DESCRIPTION = "Advanced cloud storage hunter with multi-provider support"

# Cloud Providers
PROVIDERS = [
    {"name": "AWS S3", "url": "https://{}.s3.amazonaws.com"},
    {"name": "AWS S3 (Alt)", "url": "https://s3.amazonaws.com/{}"},
    {"name": "Google Storage", "url": "https://storage.googleapis.com/{}"},
    {"name": "Google Storage (Alt)", "url": "https://{}.storage.googleapis.com"},
    {"name": "Azure Blob", "url": "https://{}.blob.core.windows.net/container"},
    {"name": "DigitalOcean Spaces", "url": "https://{}.nyc3.digitaloceanspaces.com"}
]

MUTATIONS = ["", "-dev", "-test", "-staging", "-prod", "-backup", "-logs", "-public", "-private", ".bak"]

def run(kb):
    target = kb.get("target_domain")
    if not target: return

    # [FIX] Skip if target is an IP address
    try:
        ipaddress.ip_address(target)
        # If no exception, it is an IP. Return silently.
        return
    except ValueError:
        pass

    # [FIX] Ignore short targets to avoid false positives (e.g., "abc", "test")
    keyword = target.split('.')[0]
    if len(keyword) < 4:
        # If the main keyword is too short, finding a bucket is unlikely/useless
        return

    # display.log is safer if available, else print
    logger = display.log if 'display' in globals() else print
    
    logger(f"Running {DESCRIPTION}...", "INFO")
    logger(f"Checking variations for keyword: [bold]{keyword}[/bold]", "INFO")

    found_buckets = []
    
    # Generate variations
    check_list = []
    for m in MUTATIONS:
        check_list.append(f"{keyword}{m}")
        check_list.append(f"{m.strip('-')}-{keyword}")

    # Remove duplicates
    check_list = list(set(check_list))

    # Scan
    for bucket_name in check_list:
        # Skip weird names generated by mutations
        if len(bucket_name) < 3 or bucket_name.startswith("-") or bucket_name.endswith("-"):
            continue

        for provider in PROVIDERS:
            url = provider["url"].format(bucket_name)
            try:
                r = requests.get(url, timeout=3, verify=False)
                
                if r.status_code == 200:
                    logger(f"Found OPEN Bucket: {url} (Provider: {provider['name']})", "CRITICAL")
                    found_buckets.append({"url": url, "status": "OPEN", "provider": provider['name']})
                    
                    # Check for listing
                    if "ListBucketResult" in r.text or "<Name>" in r.text:
                         logger(f"  > Bucket Content Listing Enabled!", "CRITICAL")
                
                elif r.status_code == 403:
                    # Protected buckets are common, we usually only care if they match the domain exactly
                    if bucket_name == keyword or bucket_name == target:
                        logger(f"Found PROTECTED Bucket: {url}", "WARNING")
                        found_buckets.append({"url": url, "status": "Protected", "provider": provider['name']})

            except:
                pass

    if found_buckets:
        kb.update("cloud_buckets", found_buckets)
